<?php

	$helper = $this->helper('RedboxDigital\LinkedinProfile\Helper\Data');
	$mandatory = $helper->getOption();

?>
<div class="field linkedinprofile <?php echo $mandatory; ?>">
    <label for="linkedinprofile" class="label"><span><?php /* @escapeNotVerified */
            echo __('Linkedin Profile URL') ?></span></label>
    <div class="control">
        <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php /* @escapeNotVerified */
        echo __('Linkedin Profile URL') ?>" class="input-text <?php echo $mandatory; ?> url validate-length maximum-length-250">
    </div>
</div>